Fix keyboard and mouse handling problem in pharo 9
lxsang/PTerm pull request #34
Opened 2022-06-16 18:08 UTC by lxsang

This PR addresses the issue #31.

In pharo 9 and up, some keys such as non printable characters or meta/control keys are not handled by #keystroke event. Instead they are catched by #keyDown event. This PR allow PTerm to catch and process both events.

The solution is partially tested

2022-06-17 18:19 UTC, Rinzwind requested changes
Looks good. I did find two small problems though. Scenario: I open Terminal and type “cat”. The first problem is that the RETURN key doesn’t work unless I click inside the window once. Then, the second problem is that when I press CTRL-C, it seems as if I also pressed CTRL-SPACE first:

<img width="124" alt="1" src="https://user-images.githubusercontent.com/1611248/174355322-44334d19-eed2-487c-8313-28f9596e4bfe.png">

For comparison, using ‘master’ in Pharo 7:

<img width="129" alt="2" src="https://user-images.githubusercontent.com/1611248/174355340-87159fb9-a51e-4be8-bfd2-29f7dfb86b5d.png">

2022-07-22 22:40 UTC, Rinzwind commented
@lxsang I tried to fix the two problems I described in my previous comment, can you take a look?

2022-07-25 07:24 UTC, lxsang commented
@Rinzwind sorry for the late reply, i'm a little bit busy right now, i'll take a look ASAP when i have spare time. Anyway, many thank for your work

2022-07-25 07:29 UTC, lxsang commented on PTerm-UI/TerminalEmulatorMorph.class.st
> +				(char = 32) ifTrue: [ ^ down downcall: 0 ].
So we have the same problem on Pharo 7 (master). We need to synchronise the common code between the two branches.

I will integrate this modification on master, then rebase this branch to master.

2022-08-06 17:41 UTC, lxsang commented
i will integrate this to Pharo 9 branch. I propose we integrate this branch to master, the old master becomes the pharo7-stable branch.

Any further feature development, bug fix and improvement should be integrated to master to support newer version of Pharo.

We only accept PRs for bug fix on pharo7-stable branch, PRs on new features should not be integrated to this branch.

2022-08-06 17:41 UTC, merged