Override fb term open menu item
lxsang/PTerm pull request #69
Opened 2024-11-29 15:43 UTC by hernanmd

Enable override menu item to open the Terminal in the P13 File Browser

2024-11-29 20:25 UTC, Rinzwind commented
@hernanmd Thanks! I made two improvements to `#openTerminalOn:` on PTTerminalInterface (commits 9ed89f6535fb153c and 1b61e45de1647b4d).

2024-11-29 20:30 UTC, Rinzwind commented
@lxsang I put you as reviewer. This is for issue #62. Two things to note:

* The package ‘PTerm-Pharo13’ depends on the changes in [NewTools pull request #916](https://github.com/pharo-spec/NewTools/pull/916).
* The first two commits in this pull request are from [pull request #68](https://github.com/lxsang/PTerm/pull/68), you should maybe merge that one first.

2024-11-30 13:49 UTC, lxsang requested changes

2024-11-30 13:49 UTC, lxsang commented on BaselineOfPTerm/BaselineOfPTerm.class.st
> +	spec for: #'pharo13.x' do: [
This spec may be reusable for any future version of Pharo,  not just Pharo 13. It is better if we can generalize it (something like >= pharo13)

2024-11-30 13:49 UTC, lxsang commented on BaselineOfPTerm/BaselineOfPTerm.class.st
> +		spec package: 'PTerm-Pharo13'.
Same here, for future-proof, I'd avoid naming the package to a specific version of Pharo, Something like `PTerm-SystemInterface` or `PTerm-SystemHook` should be good

2024-11-30 13:49 UTC, lxsang commented on PTerm-Pharo13/PTTerminalInterface.class.st
> +	#category : #'PTerm-Pharo13-Utilities'
Same here for future proof naming

2024-11-30 13:51 UTC, lxsang commented
I merge the #68, a rebase may be needed to remove duplicated commits

2025-02-08 21:20 UTC, Rinzwind commented on BaselineOfPTerm/BaselineOfPTerm.class.st
> +	spec for: #'pharo13.x' do: [
I’m not sure MetacelloBaselineConstructor provides a way to express that the block is for future Pharo versions as well, so this may not be generalizable other than by directly checking the SystemVersion.

2025-02-08 21:20 UTC, Rinzwind commented on BaselineOfPTerm/BaselineOfPTerm.class.st
> +		spec package: 'PTerm-Pharo13'.
I renamed the package to ‘PTerm-SystemInterface’.

2025-03-06 13:32 UTC, lxsang commented on BaselineOfPTerm/BaselineOfPTerm.class.st
> +	spec for: #'pharo13.x' do: [
Yes, i made a modification in 0f952994bdf27e1a20389926a041cad9447f499c that directly checks  the system version, during the 'construction' of the spec. @Rinzwind  Could you take a look ?

2025-03-07 22:36 UTC, Rinzwind commented on BaselineOfPTerm/BaselineOfPTerm.class.st
> +	spec for: #'pharo13.x' do: [
Looks OK! I tested that in Pharo 12 the package ‘PTerm-SystemInterface’ is not loaded, and that in Pharo 13 it is loaded.

2025-03-08 00:14 UTC, merged